### ISSUE TITLE
Lua Error when opening FastMythPort window

### ISSUE THREAD

**Issue by ThatGuy116** [BloodDragon2580/FastMythPort#4]
40x FrameXML/ActionButtonTemplate.xml:268 Unknown: Couldn't find relative frame: $parent

**Comment by BloodDragon2580** [comment]
Hmm strange, can you post the complete error please. Not just the first line?

It works for me and my friends without any problems.

**Comment by ThatGuy116** [comment]
This was the whole line from Bug grabber. I just looked into it again, trying to re-install the addon to see if it helps, apparently I had one of the earlier versions which is no longer recognized by Curseforge, hence why it never updated and had old lua errors.

After deleting it manually and installing it over again it's working fine :)

**Comment by BloodDragon2580** [comment]
ok nice^^
